-- 此脚本由工具生成

Localization = {
    Day = "天",
    DaysAgo = "天前",
    Hour = "时",
    Hour_1 = "小时",
    HoursAgo = "小时前",
    Minute = "分",
    Minute_1 = "分钟",
    MinutesAgo = "分钟前",
    Second = "秒",
    JustNow = "刚刚",
    BackToLogin = "返回登录",
    KeepToWait = "继续等待",
    LoginFailure = "与服务器间的连接已断开,请重新登录！",
    ConnectFailure = "您已与服务器断开连接，是否尝试重连？",
    NetUnreachable = "无网络服务,请检查您的网络！",
    NetTimeOut = "连接超时,请检查您的网络！",
    NetError = "网络异常,请检查您的网络！",
    NetReceiveZero = "接收未完成",
    InvaildUrl = "无效的远端地址",
    Reconnect = "重新连接",
    Connecting = "网络不佳，是否尝试进行第%d次重新连接？",
    Cancel = "取消",
    Confirm = "确认",
    Continue = "继续",
    CopySuccess = "复制成功",
    Go = "前往"
}
